# Generated by Django 3.2.23 on 2023-12-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_userprofile_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
