# Generated by Django 3.2.23 on 2023-12-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20231221_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='aadhar_upload',
            new_name='aadhar',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='certificate_upload',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='pan_card_upload',
            new_name='pan',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='photo_upload',
            new_name='photo',
        ),
    ]
